package.json, src/index.ts
This renames the package to vote-imagetools since the focus of the package has grown larger than just srcsets
=> publish package as site-imagetools

docs/directives.md, packages/core/src/transforms/__tests__/__file_snapshots__/aspect-transform-basic-0, packages/core/src/transforms/__tests__/__file_snapshots__/aspect-transform-w--fit-&-background-0, packages/core/src/transforms/__tests__/__file_snapshots__/aspect-transform-w--fit-0, packages/core/src/transforms/__tests__/__file_snapshots__/aspect-transform-w--fit-and-position-0, packages/core/src/transforms/__tests__/__file_snapshots__/aspect-transform-w--height-0, packages/core/src/transforms/__tests__/__file_snapshots__/aspect-transform-w--kernel-0, packages/core/src/transforms/__tests__/__file_snapshots__/aspect-transform-w--width-&-height-0, packages/core/src/transforms/__tests__/__file_snapshots__/aspect-transform-w--width-0, packages/core/src/transforms/__tests__/resize.spec.ts, packages/core/src/transforms/resize.ts
[Add aspect ratio support to the resize directive](https://github.com/JonasKruckenberg/imagetools/issues/63)
This change adds an `aspect` keyword used in the resize transform.
Use Cases:
- If aspect & width are provided, calculate height to match
- If aspect & height are provided, calculate width to match
- If only aspect is provided, calculate both height and width.  This will keep the the original image as large as possible, meaning only one dimension will be cropped to get the correct aspect ratio
- If height & width are both provided, ignore the `aspect` keyword
**Tests**
Test coverage added to the `core` package, covering the cases above as well as combinations with fit, background, position, and kernel
=> #63: Add aspect ratio support to the resize directive

docs/guide/getting-started.md
The `metadata` directive was missing in this example, so the code did not work as instructed.
Easiest contributor badge ever!
=> Fix missing `metadata` directive in example

.changeset/fix140.md, packages/vite/src/index.ts
Fixes #140 
None
PR?)
No
Am not sure if cloning an image has performance implications. Perhaps could be optimised by only cloning if there is more than one image format in the array, but didn't see worth premature optimisation.
=> fix: clone image in vite plugin to avoid dev server issue (#140)

.changeset/resolve-configs.md, docs/guide/extending.md, packages/rollup/src/__tests__/main.test.ts, packages/rollup/src/index.ts, packages/rollup/src/types.ts, packages/vite/src/__tests__/main.test.ts, packages/vite/src/index.ts, packages/vite/src/types.ts
This pull request relates to #139. It adds ability to supply a custom `resolveConfigs`.
If you don't set property in config everything works the same as before. You can supply a function that will be called in place of the default `resolveConfigs`. If this function doesn't return a value, the existing `resolveConfigs` is called, otherwise the result of the custom `resolveConfigs` is used.
Below is an example of a custom implementation. If you add `?glowsite=<preset>` to an image import it will generate images with preset widths in webp format.
```
const defaultPresets = {
default: {widths: [300, 800, 1200]}
}
export …
```
=> feat: Add ability to override resolveConfigs in vite plugin

.changeset/tasty-crews-allow.md, packages/rollup/package.json, packages/vite/package.json
Fixes the error "Cannot find module 'vite-imagetools' or its corresponding type declarations."
=> Fix path to typings

docs/directives.md
Docs update
Nothing
PR?)
No
/
---
The current example doesn't work:
```js
import Images from 'example.jpg?avif&quality=10,50,75'
```
Use semicolons instead:
```js
import Images from 'example.jpg?avif&quality=10;50;75'
```
=> fix(doc): use semicolon instead of comma

.changeset/fluffy-ravens-flow.md, packages/rollup/src/__tests__/main.test.ts, packages/rollup/src/index.ts, packages/vite/src/__tests__/main.test.ts, packages/vite/src/index.ts
Fixes the conditional reveal of metadata when using the `defaultDirectives` option.
- ~~**What is the new behavior (if this is a feature change)?**~~
- ~~**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this
PR?)~~
Should fix issue #355.
=> fix: conditionally reveal metadata when using defaultDirectives

.changeset/friendly-kangaroos-relax.md, packages/core/package.json, pnpm-lock.yaml
Fix
Make it so that Vitest isn't installed for all users of imagetools
PR?)
Unlikely. A user could have updated in the past couple of hours, written Vitest tests, and be depending on getting it via `imagetools`, but I wouldn't worry about that given that it's unlikely and at worst will only affect tests
=> fix: don't include Vitest as dependency

.changeset/wild-students-lay.md, packages/core/package.json, packages/rollup/package.json, packages/vite/package.json
Fixes https://github.com/JonasKruckenberg/imagetools/issues/402
Resolves `.mjs` files
PR?)
This PR would only be breaking if a user is reaching into the internals of the package. That would become disallowed. However, I don't think there was every a reason to do that or that it's something that should be supported
=> fix: add an exports map

.changeset/tidy-ducks-stare.md, packages/rollup/package.json, packages/rollup/src/index.ts, packages/vite/package.json, packages/vite/src/index.ts, pnpm-lock.yaml
- **What kind of change does this PR introduce?** Fix / refactoring
This bundles `imagetools-core` and exports its functionality from the bundler packages. I tried to use the `Picture` type from `vite-imagetools` and the only way I could do it was to install `imagetools-core` in addition to `vite-imagetools`. This will make it easier for people to use the packages so that they only need to add `vite-imagetools` to their `package.json`
- **Does this PR introduce a breaking change?** No
=> Bundle imagetools-core

.changeset/new-parents-appear.md, .github/workflows/release.yml, package.json, packages/rollup/package.json, packages/vite/package.json, pnpm-lock.yaml
- **What kind of change does this PR introduce?** Fix
- **What is the new behavior (if this is a feature change)?** Don't bundle `imagetools-core`
- **Does this PR introduce a breaking change?** Just reverts to previous behavior
- **Other information**: Apparently rollup doesn't bundle types, which makes bundling the core library in not work all that well
=> fix: revert bundling of imagetools-core

.changeset/six-cougars-grin.md, docs/directives.md, docs/interfaces/core_src.ResizeOptions.md, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-2-m-22-mwithout-enlargement-2-m-22-mtransform-2-m-22-mw-aspect-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-2-m-22-mwithout-enlargement-2-m-22-mtransform-2-m-22-mw-height-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-2-m-22-mwithout-enlargement-2-m-22-mtransform-2-m-22-mw-multiple-dimensions-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-2-m-22-mwithout-enlargement-2-m-22-mtransform-2-m-22-mw-width-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-2-m-22-mwithout-enlargement-2-m-22-mtransform-2-m-22-mw-width-height-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-2-m-22-mwithout-enlargement-2-m-22-mtransform-2-m-22-mw-width-height-aspect-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-2-m-22-mwithout-reduction-2-m-22-mtransform-2-m-22-mw-aspect-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-2-m-22-mwithout-reduction-2-m-22-mtransform-2-m-22-mw-height-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-2-m-22-mwithout-reduction-2-m-22-mtransform-2-m-22-mw-multiple-dimensions-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-2-m-22-mwithout-reduction-2-m-22-mtransform-2-m-22-mw-width-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-2-m-22-mwithout-reduction-2-m-22-mtransform-2-m-22-mw-width-height-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-2-m-22-mwithout-reduction-2-m-22-mtransform-2-m-22-mw-width-height-aspect-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-without-enlargement-transform-w-aspect-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-without-enlargement-transform-w-height-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-without-enlargement-transform-w-multiple-dimensions-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-without-enlargement-transform-w-width-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-without-enlargement-transform-w-width-height-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-without-enlargement-transform-w-width-height-aspect-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-without-reduction-transform-w-aspect-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-without-reduction-transform-w-height-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-without-reduction-transform-w-multiple-dimensions-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-without-reduction-transform-w-width-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-without-reduction-transform-w-width-height-1-snap.png, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-src-transforms-tests-resize-spec-ts-without-reduction-transform-w-width-height-aspect-1-snap.png, packages/core/src/transforms/__tests__/resize.spec.ts, packages/core/src/transforms/resize.ts
Added boolean `withoutEnlargement` and `withoutReduction` flags to prevent image resizing if active and the calculated with or height exceeds or subceeds the original size.
Default behavior remains the same but users can add `&withoutEnglargment` or `&withoutReduction` to prevent unwanted resizing. Images are still created as Sharp sees fit.
PR?)
No breaking change as `withoutEnlargement` and `withoutReduction` are opt-in per Sharp's API.
Closes #460 and touches #257. 
1. Check …
=> feat: add withoutEnlargment + withoutReduction

.changeset/nervous-ads-draw.md, packages/rollup/package.json, packages/vite/package.json
- **What kind of change does this PR introduce?** Fix
- **What is the new behavior (if this is a feature change)?** Put `types` first. https://publint.dev/vite-imagetools@4.0.14
- **Does this PR introduce a breaking change?** No - bug fix
=> fix: types exports must come first

packages/core/README.md
One of the examples in the README was missing the `generateTransforms` import.
Fix missing import in an example README.
All examples in the README work when used.
PR?)
No
=> Update missing import in README

.changeset/pink-yaks-jam.md, package.json, packages/vite/src/index.ts
It adds support for Vite's `base` config in the dev server. This fixes issues with serving assets through imagetools when using a custom backend, such as Rails.
Fixes #396.
The URL prefix used to watch for imagetools requests is now `${viteConfig.base}/@imagetools/` instead of just `/@imagetools/`. This allows for things like Rails to properly forward those requests to the Vite dev server.
PR?)
I don't think so, no.
=> support Vite's `base` config when using the dev server

.changeset/moody-parents-float.md, packages/vite/src/index.ts
- **What kind of change does this PR introduce?** bug fix
- **What is the new behavior (if this is a feature change)?** fixes a regression from https://github.com/JonasKruckenberg/imagetools/pull/489
- **Does this PR introduce a breaking change?** no
=> fix: ensure leading slash in generated URL

.changeset/unlucky-maps-burn.md, packages/vite/src/index.ts
Tested locally with different base param value
base: "http://localhost:3000" — http://localhost:3000/@imagetools/d99ae1dc2434acf7a940ad240f75c5e9373463f2
base: "http://localhost:3000/base" — http://localhost:3000/base/@imagetools/d99ae1dc2434acf7a940ad240f75c5e9373463f2
base: "http://localhost:3000/base/" — http://localhost:3000/base/@imagetools/d99ae1dc2434acf7a940ad240f75c5e9373463f2
base: "/base/" — /base/@imagetools/d99ae1dc2434acf7a940ad240f75c5e9373463f2
base: "/base" — /base/@imagetools/d99ae1dc2434acf7a940ad240f75c5e9373463f2
base: "/" — /@imagetools/d99ae1dc2434acf7a940ad240f75c5e9373463f2
base: "" — /@imagetools/d99ae1dc2434acf7a940ad240f75c5e9373463f2
Closes: #500 
Fix
- …
=> fix: basePath must support not only path, but url in watch mode

packages/vite/src/__tests__/main.test.ts, packages/vite/src/index.ts, packages/vite/src/utils.ts
The base path handling has had a couple bugs recently and has been subtly tricky to get right, so adding a test to make sure we cover the various cases
=> add test for base path handling

.changeset/light-singers-cheer.md, packages/rollup/README.md
Do a final release of the Rollup plugin that deprecates it before removal
=> Add deprecation notice for Rollup plugin

.changeset/eight-pets-arrive.md, packages/vite/src/index.ts
closes https://github.com/JonasKruckenberg/imagetools/issues/521
=> fix: don't match extensions in query string

.changeset/brown-jars-protect.md, .changeset/ninety-pugs-burn.md, docs/directives.md, docs/guide/getting-started.md, examples/vite-simple/README.md, examples/vite-simple/main.js, packages/core/src/lib/parse-url.ts, packages/core/src/lib/resolve-configs.ts, packages/core/src/transforms/__tests__/format.spec.ts, packages/core/src/transforms/format.ts, packages/vite/README.md, packages/vite/src/__tests__/main.test.ts, packages/vite/src/index.ts
- **What kind of change does this PR introduce?** Feature
- **What is the new behavior (if this is a feature change)?** 
Simplify ability to provide defaults. Image format is now specified with `format=` and output format is now specified with `as=`.
Formats are most often specified with `defaultDirectives` and presets and this makes using both of those features much easier at the expense of making exceptions slightly more verbose. It also adds clarity as there's only a single way to do things vs multiple
You can see how much simpler this becomes in the example in https://github.com/JonasKruckenberg/imagetools/issues/536
- **Does this PR introduce a breaking change?** Yes
- **Other information**: Closes https://github.com/JonasKruckenberg/imagetools/issues/536
=> Make output format a URL parameter value instead of key

packages/vite/src/index.ts
If you had `defaultDirectives: new URLSearchParams({ w: '100;200;400;800' })` and `image.png?w=300,500` then you'd end up with `[[100, 200, 400, 800], [300, 500]]` which would then get combined into 8 different sizes by `resolveConfig`.
Assuming `defaultDirectives` is supposed to be used for defaults then this seems incorrect. It's possible that the intended usage is for the user to check whether a parameter is specified before providing it, but this seems unlikely as the non-function form would only work if the user never provided any per-image override. In that case, the design would be brittle and the name would be misleading, so I'm assuming that's not how it's to be used
=> fix: combine directives with defaultDirectives correctly

.changeset/few-hairs-lay.md, packages/core/package.json, packages/core/rollup.config.js, packages/vite/package.json, packages/vite/rollup.config.js
- **What kind of change does this PR introduce?** improvement
- **What is the new behavior (if this is a feature change)?** only build an ESM version. This will make compilation twice as fast and make the package only half as large. It also makes debugging easier because you don't have to figure out which version was loaded as there's only a single version
- **Does this PR introduce a breaking change?** Yes
=> breaking: drop CJS support

.changeset/loud-penguins-nail.md, packages/vite/src/index.ts
Fix a bug where `vite build -w` produces `/@imagetools/*` URLs, when it should be producing image outputs.
PR?)
=> fix: correct detection for Vite build vs serve mode

.changeset/tender-jobs-double.md, packages/core/src/util.ts
Bug fix in order to ensure that generated image IDs are consistent across environments.
Image IDs are now generated from a relative file path instead of an absolute one which should ensure their consistency across environments.
PR?)
Yes. Generated image IDs will change so tests which rely on these IDs may break.
=> chore: generate image IDs from relative filepath

.changeset/kind-dogs-walk.md, packages/vite/src/index.ts, packages/vite/src/types.ts
If you want to implement [the fancy `sizes` support that Next.js has](https://nextjs.org/docs/pages/api-reference/components/image#sizes), then you need to know the original image width in order to decide what variants to generate
=> feat: make image metadata available in `defaultDirectives`

.changeset/beige-mails-notice.md, packages/vite/src/types.ts
This will be helpful to reference the types of our options individually
=> chore: create and expose type aliases

.changeset/afraid-news-trade.md, packages/vite/src/index.ts
I forgot that the `types.ts` file isn't actually used for the types. Maybe we should rename it `internal.ts` or something
=> fix: actually expose recently added types

.changeset/witty-seahorses-rhyme.md, packages/core/src/transforms/__tests__/format.spec.ts, packages/core/src/transforms/format.ts
closes https://github.com/JonasKruckenberg/imagetools/issues/570
=> feat: allow usage of all supported sharp output formats

.changeset/orange-actors-double.md, packages/vite/src/index.ts
had a `string` and `number` so they didn't get deduped. make everything a `string` when adding to the `Set`
=> fix: avoid duplicate widths in output

.changeset/two-ears-matter.md, packages/core/src/lib/metadata.ts, packages/core/src/types.ts, packages/vite/src/index.ts, packages/vite/src/utils.ts, tsconfig.json
No tests needed. Docs need no change.
Fixes failed compilation when `moduleResolution` is set to `nodenext` by updating the tsconfig to use it.
Also enabled `verbatimModuleSyntax` to get rid of some warnings.
Not applicable.
PR?)
To my knowledge, none. The updated packages already use ESM, so there should be no breaking change.
=> fix: TypeScript fixes

.changeset/shaggy-otters-talk.md, packages/vite/src/utils.ts
It might be less reliable since it's newer? (example: https://github.com/nodejs/node/issues/51031)
People are reporting weird errors (https://github.com/sveltejs/kit/discussions/11098) and this is my best guess at the moment
=> fix: avoid using fs/promises

.changeset/afraid-books-notice.md, packages/vite/src/index.ts
* [*] I have read [the contributing guidelines](../CONTRIBUTING.md)
* [*] I have added a changeset, if applicable
Bug fix
Transformed images will be written to the file system without URL-encoding, just like the original files. 
PR?)
No
=> fix: use URI-decoded pathname when emitting file

.changeset/quiet-bulldogs-appear.md, packages/vite/src/index.ts
Fixes: https://github.com/JonasKruckenberg/imagetools/issues/568
Add vite `origin` support for image urls in development.
=> Add vite `origin` support for image urls in development

.changeset/long-baboons-dream.md, packages/vite/src/__tests__/main.test.ts, packages/vite/src/index.ts
Bug fix
`avif` files that are from the cache directory have the correct format
PR?)
No
Currently when an `avif` file read from cache, Sharp metadata returns `{format: 'heif', compression: 'av1'...}` causing the file extension and Picture mime type to be incorrect.
https://github.com/lovell/sharp/issues/2504 
https://github.com/lovell/sharp/issues/3746
The new test for `cache.avifFormat` will fail on imagetools@7.0.0
=> fix: avif format

.changeset/breezy-melons-wave.md, packages/vite/src/__tests__/main.test.ts, packages/vite/src/index.ts, packages/vite/src/utils.ts
This PR fixes an issue that we've been experiencing in https://github.com/huntabyte/shadcn-svelte/pull/978 where the hash for the generated image ID is different when it's computed on different machines. The goal of that PR was to cache the images so that they can be utilized across our GH runners.
The source of the issue is the `mtime` stat from the image file, which seemingly differs from machine to machine, causing the hash to generate a different id, resulting in a cache MISS. Instead, `mtime` has been replaced for the `size` stat, which (in conjunction with the image config and file url) should provide sufficient uniqueness for the hash.
---
Bug fix
- **What is the new …
=> fix: Consistent image ID hashes across machines

.changeset/tough-scissors-watch.md, packages/core/package.json, packages/vite/package.json, pnpm-lock.yaml
closes https://github.com/JonasKruckenberg/imagetools/issues/659
=> fix: attempt to make sharp dependency declaration compatible with yarn

.changeset/new-otters-turn.md, packages/vite/src/index.ts
This change contains a bug fix for the feature introduced in pull request #690. The server origin option usually contains a  protocol scheme identifier followed by a double slash, e.g. "http://localhost:1234". Nodes POSIX path implementation is not meant to join URLs, which means the double slash is converted to a single slash, resulting in an invalid URL, e.g "http:/localhost:1234". Using url-join instead ensures the result will be a valid URL.
Added new dependency: [url-join](https://github.com/jfromaniello/url-join), which seams to be the safest option
=> Fix url concatenation for dev mode with origin set in server options

.github/workflows/test.yml, packages/core/rollup.config.js, packages/vite/rollup.config.js
I wasn’t able to build the project using Node v22 because it used the legacy import assertion syntax. Support for this was removed from Node. To fix this, I’m reading `package.json` as to not rely on JSON module support which may be unavailable on older Node versions (?).
I’m also fixing the Github workflows so that they actually run against different Node versions and we can discover this in the future.
=> fix: remove legacy import assertion unsupported by Node v22

.changeset/fuzzy-beers-hang.md, packages/core/src/transforms/__tests__/__image_snapshots__/resize-spec-ts-aspect-transform-w-crop-horizontally-1-snap.png, packages/core/src/transforms/__tests__/resize.spec.ts, packages/core/src/transforms/resize.ts
When the aspect ratio is reduced and no width or height are given the image is now correctly cropped.
Before, if I requested an aspect ratio of 1:2 for an image with dimensions 640x800 it would not change the dimensions of the image. Now the image is correctly cropped to 400x800.
=> fix: crop horizontally when aspect ratio is reduced without width or height
